Document: noip-2.1.9
Title: Debian noip-2.1.9 Manual
Author: <insert document author here>
Abstract: This manual describes what noip-2.1.9 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/noip-2.1.9/noip-2.1.9.sgml.gz

Format: postscript
Files: /usr/share/doc/noip-2.1.9/noip-2.1.9.ps.gz

Format: text
Files: /usr/share/doc/noip-2.1.9/noip-2.1.9.text.gz

Format: HTML
Index: /usr/share/doc/noip-2.1.9/html/index.html
Files: /usr/share/doc/noip-2.1.9/html/*.html
